packages:
  - 'packages/*'

catalog:
  '@types/node': ^22.13.1
  rolldown: 1.0.0-beta.3-commit.de6e9d2
  rollup: ^4.34.7
  rollup-plugin-dts: ^6.1.1
  tsx: ^4.19.2
  typescript: ^5.7.3
  vitest: ^3.0.5
