name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup pnpm
        uses: pnpm/action-setup@v2
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: pnpm
      - run: pnpm i
      - name: run build
        run: pnpm run -r --stream build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'chore: update versions'
          commit: 'chore: update versions'
          version: pnpm run release:version
          publish: pnpm run release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
